launch:
  verbose: False
cartographer:
  enable: True
  map_resolution: 0.05
  map_publish_period: 0.2
gazebo:
  gui: True # set to false for better performances during training
  verbose: False
env:
  available_models: ['turtlebot3_bighouse', 'turtlebot3_world', 'small_warehouse', 'small_house', 'empty_world']  #, 'hospital']
  num_envs: 4
  # single_model, multiple_models, random_models
  mode: 'single_model' 
  model: 'turtlebot3_world' # for single_model
  models: ['turtlebot3_bighouse', # for multiple_models, random_models choose between all available worlds
           'turtlebot3_world',
           'small_warehouse',
           'small_house']
robot:
  random_pose: True
  pose:
    x: 0.0
    y: 0.0
    yaw: 0.0


